// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ppwfpteyygtradqxaekn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwd2ZwdGV5eWd0cmFkcXhhZWtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3MjE4MjIsImV4cCI6MjA1ODI5NzgyMn0.SiAsYXW73w8eJs-a3Vatnu6VoDbbZmbM19Xdq34IjiQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);